// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:25c4becf-caf0-41f6-baee-1aff24db198d',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reefcoinmarketplace-hosting-mobilehub-1643278897',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dvnb8utp5yr72.cloudfront.net',
    'aws_mobile_analytics_app_id': '2fd11a09d5074fd3aaa16419c901e737',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3a86ad12-5163-49de-a7f8-0a517422751e',
    'aws_project_name': 'ReefCoinMarketplace',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'reefcoinmarketplace-mobilehub-1643278897',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_qW1R7W33E',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5jn77t6mb5ermjg7f2uupoch00',
}

export default awsmobile;